In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import binary_crossentropy

/Users/andreasainz/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
#Create data for XOR fucntion
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [3]:
# Define the model
model = Sequential()

# Single hidden layer with sigmoid activation (experiment with the number of units)
model.add(Dense(2, input_dim=2, activation='sigmoid'))  # Minimum 2 hidden units for XOR
model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.1), loss=binary_crossentropy, metrics=['binary_accuracy']) #metrics=['accuracy']

# Train the model
history = model.fit(X, y, epochs=100, verbose=1)  # Train for sufficient epochs

Epoch 1/100


/Users/andreasainz/Library/Python/3.9/lib/python/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step - binary_accuracy: 0.2500 - loss: 0.6947
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.5000 - loss: 0.6906
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - binary_accuracy: 0.5000 - loss: 0.6853
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.7500 - loss: 0.6812
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.7500 - loss: 0.6777
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.7500 - loss: 0.6738
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.7500 - loss: 0.6698
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.5000 - loss: 0.6660
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.5000 - loss: 0.6615
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.7500 - loss: 0.6563
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.7500 - loss: 0.6509
Epoch 12/100
1/1 

In [4]:
# Evaluate the model
predictions = model.predict(X)
binary_predictions = (predictions > 0.5).astype(int)

# Print Results
print("Input:\n", X)
print("Expected Output:\n", y.flatten())
print("Predicted Output:\n", binary_predictions.flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Input:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Expected Output:
 [0 1 1 0]
Predicted Output:
 [0 1 1 0]


In [5]:
# Get weights and biases of each layer
for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()
    print(f"Layer {i + 1}:")
    print(f"Weights:\n{weights}")
    print(f"Biases:\n{biases}")

Layer 1:
Weights:
[[-5.3237896 -7.6171165]
 [-5.269215  -7.0431647]]
Biases:
[7.85457  3.142078]
Layer 2:
Weights:
[[ 8.378108]
 [-8.696453]]
Biases:
[-3.9358552]
